export const routes = {
  home: '/',
  last30Days: '/new-releases/last-30-days',
  thisWeek: '/new-releases/this-week',
  nextWeek: '/new-releases/next-week',
  releaseCalendar: '/new-releases/release-calendar',
  bestOfTheYear: '/top/best-of-the-year',
  popularIn2022: '/top/popular-in-2022',
  allTimeTop250: '/top/all-time-250',
  platforms: '/browse/platforms',
  stores: '/browse/stores',
  collections: '/browse/collections',
  developers: '/browse/developers',
  pc: '/platforms/pc',
  playstation: '/platforms/playstation',
  xbox: '/platforms/xbox',
  action: '/genres/action',
  strategy: '/genres/strategy',
  rpg: '/genres/rpg',
  shooter: '/genres/shooter',
  sport: '/genres/sport',
  profile: '/profile',
};
