import '../globals.css';
import type { Metadata } from 'next';
import { Tektur } from 'next/font/google';

const tektur = Tektur({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={tektur.className}>{children}</body>
    </html>
  );
}
