import '../../../globals.css';
import type { Metadata } from 'next';
import MonthsLinks from '@/components/shared/MonthLinks';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <section>
      <h1 className='headingText'>Release Calendar</h1>
      <MonthsLinks />
      {children}
    </section>
  );
}
